name: Database backup

# TODO: schedule workflow to run nightly?
on:
   push:
      branches:
         - db-backup

jobs:
   backup:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v4
         -
            # https://github.com/oven-sh/setup-bun
            uses: oven-sh/setup-bun@v2
         -
            run: bun install
         -
            run: bun db_backup/index.ts
            # env:
            #    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
