name: Database backup

on:
   push:
      branches:
         - db-backup

jobs:
   backup:
      runs-on: ubuntu-latest
      steps:
         -
            uses: actions/checkout@v4
         -
            uses: oven-sh/setup-bun@v2
         -
            run: bun i wrangler
         -
            run: bun run wrangler --version
         -
            uses: cloudflare/wrangler-action@v3
            with:
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_DB_BACKUPS }}
         # -
         #    run: bun db_backup/index.ts
