name: Database backup
permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: oven-sh/setup-bun@v2
      -
        run: bun install
      -
        run: bun run db_backup/index.ts
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_DB_BACKUPS }}
