name: Database backup

on:
  push:
    branches:
      - db-backup

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: oven-sh/setup-bun@v2
      -
        run: bun db_backup/index.ts
